# Agriculture Bot Searcher Configuration
# Copy this file to config.local.yml and modify as needed

# Ollama Configuration
ollama:
  base_port: 11434          # Starting port for Ollama instances
  num_instances: 3          # Number of Ollama instances to use
  model: "gemma3:1b"       # Default model to use
  timeout: 60              # Request timeout in seconds
  max_retries: 2           # Maximum retry attempts

# Agent Configuration
agents:
  max_agents: 6            # Maximum number of agents to deploy
  default_agents: 3        # Default number of agents
  roles:                   # Available agent roles
    - crop_specialist
    - disease_expert
    - economics_analyst
    - climate_researcher
    - technology_advisor
    - policy_analyst

# Search Configuration
search:
  default_searches: 2      # Default searches per agent
  max_searches: 5          # Maximum searches per agent
  timeout: 30              # Search timeout in seconds
  agriculture_domains:     # Trusted agricultural domains (higher relevance)
    - extension.org
    - agric.gov
    - fao.org
    - usda.gov
    - icrisat.org
    - cgiar.org
    - cimmyt.org
    - irri.org
    - croplife.org
    - agprofessional.com
    - agriculture.com

# Answer Generation
answers:
  exact_mode:
    max_words: 300         # Maximum words for exact answers
    style: "practical"     # Answer style: practical, academic, simple
  detailed_mode:
    max_words: 1500        # Maximum words for detailed answers
    include_background: true
    include_references: true

# Web API Configuration (if using web interface)
web_api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors_enabled: true

# Logging Configuration
logging:
  level: "INFO"            # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/agri_bot.log"

# Performance Tuning
performance:
  parallel_processing: true
  cache_results: false     # Enable result caching (experimental)
  cache_duration: 3600     # Cache duration in seconds
